Repository FC-DEV-FinalProject/FinalProject_Be3C_BE, pull requests merged in 2024-12, with the labels that each got.

#195 feat : 전략 상세 그래프 기능 구현 #153
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Strategy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyGraphAnalysis.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyIndicatorsCalculator.java
Labels: FEATURE

#194 refactor: 회원 관리 리팩토링
  src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/MemberManagementController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/MemberGetResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/MemberManagementPatchRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberRole.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberSearchType.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/WebConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/MemberManagementControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceImplTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImplTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceTest.java
Labels: REFACTOR

#202 update : 전략 상세 조건 검색 - 운용 기간 추가 #196
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategySearchRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
Labels: UPDATE

#221 전략 상세 - methodId 추가 #220
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
Labels: UPDATE

#225 refactor: 이메일 찾기 및 비밀번호 재설정 리팩토링
  src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/FindEmailRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/LoginRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/handler/MemberExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
  src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/MemberManagementControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImplTest.java
Labels: REFACTOR

#232 Update : 전략 목록 수정 #203
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MainPageAnalysisDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MainPageAverageIndicator.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderNickNameListResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyListRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListServiceImpl.java
Labels: UPDATE

#236 전략 상세 페이지 그래프 재반영 #153
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyGraphAnalysis.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyIndicatorsCalculator.java
Labels: UPDATE

#238 fix: 토큰 재발급 이슈 해결
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/RedisConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
  src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java
  src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java
  src/test/java/com/be3c/sysmetic/global/config/security/JwtTokenProviderTest.java
Labels: FIX

#241 Update : currentCapitalReductionRate 응답에 추가 #203
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyIndicatorsCalculator.java
Labels: UPDATE

#245 update : 대표전략 분석 지표 기능 개발 #203
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
Labels: UPDATE

#246 update : 엔드 포인트 추가 #203
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageControllerDocs.java
Labels: UPDATE

#247 :startdate 수정 #203
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
Labels: UPDATE

#268 Refactor : 메인 페이지 트레이더 이미지 추가 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SmScoreTopFive.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderRankingDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MainPageRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
Labels: REFACTOR

#272 refactor: 회원 관련 리팩토링
  src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/MemberManagementController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/WebConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImplTest.java
Labels: REFACTOR

#280 Refactor : 메인 페이지 분석 그래프 - 기간 선택 제거 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyGraphAnalysisRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
Labels: REFACTOR

#292 전략 상세 페이지 그래프 데이터 한 번에 전송 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAnalysisOption.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAnalysisResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
Labels: UPDATE

#295 전략 목록 알고리즘별 검색 - DEFENSIVE 방어형 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
Labels: UPDATE

#296 전략 목록 알고리즘별 검색 DEFENSIVE 방어형 순위 수정 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
Labels: UPDATE

#301 fix: 토큰 에러 해결
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
Labels: FIX

#306 엑셀 파일 업로드 시 그래프 레포지토리에 데이터 저장 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceImpl.java
Labels: UPDATE

#311 update: tokenProvider 수정
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
Labels: UPDATE

#315 전략 상세 분석 지수 업데이트 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
Labels: UPDATE

#318 일간 분석 삭제 #255
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
Labels: UPDATE
