Repository FC-DEV-FinalProject/FinalProject_Be3C_BE, pull requests merged in 2024-11, with the labels that each got.

#34 feature: trader strategy registration #6
  build.gradle
  src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/InsertStrategyRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatusCode.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/AccountImage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Daily.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Method.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Monthly.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Stock.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Strategy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyApprovalHistory.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStatistics.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStockReference.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyBadRequestException.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/handler/StrategyExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MethodRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StockRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStockReferenceRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/validation/CycleValidator.java
  src/main/java/com/be3c/sysmetic/domain/strategy/validation/ValidCycle.java
  src/main/java/com/be3c/sysmetic/global/common/response/ApiResponse.java
  src/main/java/com/be3c/sysmetic/global/common/response/ErrorCode.java
  src/main/java/com/be3c/sysmetic/global/common/response/SuccessCode.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/StrategyServiceImplTest.java
Labels: FEATURE

#36 feature: trader strategy modification and delete #9
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveStrategyRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Method.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Monthly.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Strategy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyBadRequestException.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/handler/StrategyExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStockReferenceRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyServiceImpl.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/InsertStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/UpdateStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyServiceTest.java
Labels: FEATURE

#44 feat: 로그인, JWT, Security #15
  build.gradle
  src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/LoginRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/RedisConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/CustomUserDetails.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
  src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java
  src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
  src/test/java/com/be3c/sysmetic/global/config/security/JwtTokenProviderTest.java
Labels: FEATURE

#47 Feature/management daily data #20
  .gitignore
  src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/DailyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MonthlyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/PageResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveDailyRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveDailyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveStrategyRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/AccountImage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Daily.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Method.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Monthly.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Stock.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Strategy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyApprovalHistory.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStatistics.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStockReference.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyCalculator.java
  src/main/java/com/be3c/sysmetic/domain/strategy/validation/DailyDateValidator.java
  src/main/java/com/be3c/sysmetic/domain/strategy/validation/ValidDailyDate.java
  src/main/java/com/be3c/sysmetic/global/util/doublehandler/DoubleHandler.java
  src/main/resources/application.properties
  src/test/java/com/be3c/sysmetic/admin/Method/MethodRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/InsertStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/UpdateStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyServiceTest.java
Labels: FEATURE

#49 feature : strategy statistics #48
  src/main/java/com/be3c/sysmetic/SysmeticApplication.java
  src/main/java/com/be3c/sysmetic/domain/strategy/config/SchedulerConfiguration.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatisticsResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Stock.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStatistics.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsServiceImpl.java
Labels: FEATURE

#53 settings: SwaggerConfig 추가 및 SecurityConfig 설정 변경 #50
  build.gradle
  src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MethodController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StockController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/DailyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveStrategyRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/handler/StrategyExceptionHandler.java
  src/main/java/com/be3c/sysmetic/global/common/response/APIResponse.java
  src/main/java/com/be3c/sysmetic/global/common/response/ApiResponse.java
  src/main/java/com/be3c/sysmetic/global/config/SwaggerConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java
Labels: SETTINGS

#51 feature: strategy account image #24
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/AccountImageRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/AccountImageResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/AccountImage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/StrategyExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/AccountImageRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/AccountImageServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/util/SecurityUtils.java
Labels: FEATURE

#57 feature: register #14
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/EmailResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/FindEmailRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/LoginRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/RegisterRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/validation/RegisterValidator.java
  src/main/java/com/be3c/sysmetic/global/config/RedisConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java
  src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java
  src/main/java/com/be3c/sysmetic/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
  src/test/java/com/be3c/sysmetic/global/config/security/RedisUtilsTest.java
Labels: FEATURE

#59 feature: find-email #18
  src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/RedisConfig.java
  src/main/java/com/be3c/sysmetic/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
Labels: FEATURE

#61 feature: reset-password #19
  src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/ResetPasswordRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/ResetPasswordLog.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/test/java/com/be3c/sysmetic/global/config/security/JwtTokenProviderTest.java
  src/test/java/com/be3c/sysmetic/global/config/security/RedisUtilsTest.java
Labels: FEATURE

#60 refactor: management strategy trader #52
  src/main/java/com/be3c/sysmetic/domain/strategy/config/SchedulerConfiguration.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/TraderStrategyController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/AccountImageRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/AccountImageResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/DailyGetResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/DailyPostRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/DailyPostResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/DailyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MethodAndStockGetResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MonthlyGetResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MonthlyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/PageResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveDailyResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyPostRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatisticsGetResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatisticsResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyStatusCode.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Daily.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStatistics.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MethodRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StockRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DailyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MethodServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MonthlyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StockServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyStatisticsServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/be3c/sysmetic/global/util/MultipartJackson2HttpMessageConverter.java
  src/test/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/InsertStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/TraderStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/UpdateStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/DeleteStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/InsertStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImplTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/UpdateStrategyServiceTest.java
Labels: REFACTOR

#74 Settings: JWT Modify #72
  src/main/java/com/be3c/sysmetic/global/config/WebConfig.java
Labels: SETTINGS

#75 update: jwt-filter #71
  src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/LoginRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java
  src/main/java/com/be3c/sysmetic/global/config/security/CustomUserDetails.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtAuthenticationFilter.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/FolderServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/InterestStrategyServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/repository/TraderStrategyRepositoryTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/TraderStrategyServiceImplTest.java
  src/test/java/com/be3c/sysmetic/global/config/security/JwtTokenProviderTest.java
Labels: UPDATE

#77 fix: 테스트 코드 수정 #76
  src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/LoginControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/strategy/service/ExcelServiceTest.java
Labels: FIX

#78 fix: StrategyApprovalServiceTest fix #76
  src/test/java/com/be3c/sysmetic/domain/strategy/service/StrategyApprovalServiceTest.java
Labels: FIX

#83 fix/login-error
  src/main/java/com/be3c/sysmetic/domain/member/exception/handler/MemberExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
Labels: FIX

#89 Feature/member management #11
  src/main/java/com/be3c/sysmetic/domain/member/controller/AccountController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/LogoutController.java
  src/main/java/com/be3c/sysmetic/domain/member/controller/MemberManagementController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/MemberGetResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/MemberManagementPatchRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/RegisterRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberRole.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberSearchRole.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberSearchType.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/handler/MemberExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/member/service/AccountServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/validation/RegisterValidator.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/AccountControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/AccountServiceTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/MemberManagementServiceTest.java
Labels: FEATURE

#117 fix: 토큰 확인용 API 에러 해결
  src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
  src/main/java/com/be3c/sysmetic/global/config/security/JwtTokenProvider.java
Labels: FIX

#119 Feature : strategy search #37
  .gitignore
  src/main/java/com/be3c/sysmetic/SysmeticApplication.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StockListDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAlgorithmOption.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAlgorithmResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategySearchRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategySearchResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dummy/InsertStrategyDummy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Strategy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStatistics.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/StrategyStockReference.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/handler/StrategySearchExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StockRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryCustom.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStockReferenceRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StockGetter.java
  src/main/java/com/be3c/sysmetic/global/common/response/APIResponse.java
  src/main/java/com/be3c/sysmetic/global/config/security/SecurityConfig.java
Labels: FEATURE

#124 fix: 프론트 전용 토큰 API 에러 해결
  src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
Labels: FIX

#123 Chore : strategy search Dummy 삭제 #37
  src/main/java/com/be3c/sysmetic/domain/strategy/dummy/InsertStrategyDummy.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StockGetter.java
Labels: FIX

#128 Feature : strategy list #8
  .gitignore
  src/main/java/com/be3c/sysmetic/domain/member/entity/EmailAuthLog.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/FindEmailLog.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberRoleChangeLog.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/MemberStateChangeLog.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategySearchControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SaveStrategyRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StockResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListByTraderDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategySearchRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderListDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderNicknameListDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyListRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListServiceImpl.java
  src/test/java/com/be3c/sysmetic/SysmeticApplicationTest.java
  src/test/java/com/be3c/sysmetic/SysmeticApplicationTests.java
  src/test/java/com/be3c/sysmetic/admin/Stock/StockRepositoryTest.java
  src/test/resources/META-INF/persistence.xml
Labels: FEATURE

#129 refactor : 전략 상세 검색 StrategySearchRepositoryImpl - Inline QStrategy 사용 #37
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepositoryImpl.java
Labels: REFACTOR

#136 update: 토큰 확인용 API 데이터 추가
  src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/TokenApiResponseDto.java
Labels: UPDATE

#138 Feature : 전략 상세 페이지 개발 strategy-detail-page#16
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/config/SchedulerConfiguration.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyDetailControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/KpRatioParametersDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/KpRatios.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MonthlyRecord.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAnalysisOption.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyAnalysisResponseDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyDetailStatistics.java
  src/main/java/com/be3c/sysmetic/domain/strategy/entity/Daily.java
  src/main/java/com/be3c/sysmetic/domain/strategy/exception/handler/StrategyDetailExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/DailyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MonthlyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyDetailRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyStatisticsRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyDetailServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/util/StrategyIndicatorsCalculator.java
Labels: FEATURE

#139 Feature : 메인 페이지 main page #38
  src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java
  src/main/java/com/be3c/sysmetic/domain/member/repository/MemberRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MainPageAverageIndicator.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/MainPageDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/SmScoreTopFive.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/TraderRankingDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MainPageRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/MainPageServiceImpl.java
Labels: FEATURE

#144 feature : 전략명으로 검색 추가 #8
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListController.java
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/StrategyListControllerDocs.java
  src/main/java/com/be3c/sysmetic/domain/strategy/dto/StrategyListByNameDto.java
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/StrategyListRepository.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListService.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategyListServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/strategy/service/StrategySearchServiceImpl.java
Labels: FEATURE

#146 fix : implement 안함 #38
  src/main/java/com/be3c/sysmetic/domain/strategy/controller/MainPageController.java
Labels: FIX

#149 fix: 프론트 전용 토큰 API 에러 해결
  src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
Labels: FIX

#154 refactor: register-member
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/RegisterRequestDto.java
  src/main/java/com/be3c/sysmetic/domain/member/entity/Member.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/MemberBadRequestException.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/handler/MemberExceptionHandler.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterService.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/main/java/com/be3c/sysmetic/domain/member/validation/RegisterValidator.java
  src/main/java/com/be3c/sysmetic/global/config/MessageConfig.java
  src/main/java/com/be3c/sysmetic/global/config/security/RedisUtils.java
  src/main/resources/errors.properties
  src/test/java/com/be3c/sysmetic/domain/member/controller/RegisterControllerTest.java
  src/test/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImplTest.java
Labels: REFACTOR

#157 update: register-member
  src/main/java/com/be3c/sysmetic/domain/member/controller/RegisterController.java
  src/main/java/com/be3c/sysmetic/domain/member/service/RegisterServiceImpl.java
  src/test/java/com/be3c/sysmetic/domain/member/controller/RegisterControllerTest.java
Labels: UPDATE

#165 fix: Hibernate/JPA exception and test code fix
  src/main/java/com/be3c/sysmetic/domain/strategy/repository/MethodRepository.java
  src/test/java/com/be3c/sysmetic/domain/member/service/MemberInfoServiceTest.java
Labels: FIX

#174 update: token-api 회원 이름 추가
  src/main/java/com/be3c/sysmetic/domain/member/controller/TokenController.java
  src/main/java/com/be3c/sysmetic/domain/member/dto/TokenApiResponseDto.java
Labels: UPDATE

#168 refactor: login
  src/main/java/com/be3c/sysmetic/domain/member/controller/LoginController.java
  src/main/java/com/be3c/sysmetic/domain/member/exception/MemberExceptionMessage.java
  src/main/java/com/be3c/sysmetic/domain/member/service/LoginServiceImpl.java
  src/test/java/com/be3c/sysmetic/domain/member/service/LoginServiceTest.java
Labels: REFACTOR
